# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'index.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        # 固定整个窗口的大小
        MainWindow.setFixedSize(980, 682)
        # MainWindow.setMaximumSize(QtCore.QSize(16777215, 800))
        MainWindow.setStyleSheet("QMainWindow{\n"
"    background-image:url(./image/bg12.jpg)\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16770000))
        self.centralwidget.setStyleSheet("QMainWindow{\n"
"    background-image: url(:/新前缀/bg.jpg);\n"
"    \n"
"    color:while;\n"
"    background-color: black;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(9, 9, 9, 9)
        self.gridLayout.setObjectName("gridLayout")
        self.left = QtWidgets.QFrame(self.centralwidget)
        self.left.setMaximumSize(QtCore.QSize(300, 16777215))
        self.left.setStyleSheet("QFrame{\n"
        "border: 2px solid white;\n"
                
# "    color:rgb(255, 255, 255);\n"
"}")
        self.left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left.setObjectName("left")
        self.pushButton = QtWidgets.QPushButton(self.left)
        self.pushButton.setGeometry(QtCore.QRect(90, 360, 112, 41))
        self.pushButton.setStyleSheet("pushButton:hover{\n"
"    background: red;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.left)
        self.label_4.setGeometry(QtCore.QRect(140, 240, 101, 31))
        self.label_4.setStyleSheet("QLabel{\n"
"    border:none\n;"
"    color:rgb(255, 255, 255);\n"
"}\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.left)
        self.label_5.setGeometry(QtCore.QRect(50, 240, 91, 31))
        self.label_5.setStyleSheet("QLabel{\n"
"    border:none\n"
"}\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.left)
        self.label_2.setGeometry(QtCore.QRect(50, 120, 90, 51))
        self.label_2.setStyleSheet("QLabel{\n"
"    border:none\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.left)
        self.comboBox.setGeometry(QtCore.QRect(150, 131, 81, 24))
        self.comboBox.setStyleSheet("comboBox{}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2.raise_()
        self.comboBox.raise_()
        self.pushButton.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.gridLayout.addWidget(self.left, 2, 0, 1, 1)
        self.top = QtWidgets.QFrame(self.centralwidget)
        self.top.setMaximumSize(QtCore.QSize(16777215, 50))
        self.top.setStyleSheet("QFrame{\n"
"border: 2px solid white;\n"
"}")
        self.top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top.setObjectName("top")
        self.label = QtWidgets.QLabel(self.top)
        self.label.setGeometry(QtCore.QRect(340, 10, 291, 31))
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"    border:none;\n"
"    color:while\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.top, 0, 0, 1, 2)
        self.right = QtWidgets.QFrame(self.centralwidget)
        self.right.setMaximumSize(QtCore.QSize(16777215, 16000000))
        self.right.setStyleSheet("QFrame{\n"
"    margin-left: 2px;\n"
"    border: 2px solid white;\n"
"}")
        self.right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right.setObjectName("right")
        self.label_3 = QtWidgets.QLabel(self.right)
        self.label_3.setGeometry(QtCore.QRect(120, 50, 101, 31))
        self.label_3.setStyleSheet("QLabel{\n"
"    border:none\n"
"}\n"
"")
        self.label_3.setObjectName("label_3")
        self.listView = QtWidgets.QListView(self.right)
        self.listView.setGeometry(QtCore.QRect(120, 90, 411, 311))
        self.listView.setStyleSheet("QListView{\n"
"    background-color:rgb(255, 255, 255);\n"
"    border:none;\n"
"}")
        self.listView.setObjectName("listView")
        self.comboBox_2 = QtWidgets.QComboBox(self.right)
        self.comboBox_2.setGeometry(QtCore.QRect(331, 431, 80, 24))
        self.comboBox_2.setStyleSheet("comboBox{\n"
"    width:50px;\n"
"    height:30px;\n"
"}")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_6 = QtWidgets.QLabel(self.right)
        self.label_6.setGeometry(QtCore.QRect(210, 410, 101, 71))
        self.label_6.setStyleSheet("QLabel{\n"
"    border:none\n"
"}\n"
"")
        self.label_6.setObjectName("label_6")
        self.pushButton_2 = QtWidgets.QPushButton(self.right)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 500, 112, 34))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3.raise_()
        self.listView.raise_()
        self.pushButton_2.raise_()
        self.comboBox_2.raise_()
        self.label_6.raise_()
        self.gridLayout.addWidget(self.right, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 980, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.comboBox.currentTextChanged['QString'].connect(self.label_4.setText)
        self.label_4.linkActivated['QString'].connect(self.pushButton.click)
        self.comboBox_2.currentTextChanged['QString'].connect(self.pushButton_2.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.listView, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.comboBox)
        MainWindow.setTabOrder(self.comboBox, self.pushButton_2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "提交"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">股票代码:</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; color:#ffffff;\">选择股票:</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("MainWindow", "股票A"))
        self.comboBox.setItemText(1, _translate("MainWindow", "股票B"))
        self.comboBox.setItemText(2, _translate("MainWindow", "股票C"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">基于大数据的股票预测系统</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">股票资讯:</span></p></body></html>"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "模型1"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "模型2"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "模型3"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">模型选择:</span></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "开始预测"))
#import text_rc
import sys

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)  # 创建一个QApplication，也就是你要开发的软件app
    MainWindow = QtWidgets.QMainWindow()    # 创建一个QMainWindow，用来装载你需要的各种组件、控件
    ui = Ui_MainWindow()                    # ui是Ui_MainWindow()类的实例化对象
    ui.setupUi(MainWindow)                  # 执行类中的setupUi方法，方法的参数是第二步中创建的QMainWindow
    MainWindow.show()                       # 执行QMainWindow的show()方法，显示这个QMainWindow
    sys.exit(app.exec_())                   # 使用exit()或者点击关闭按钮退出QApplicat
